# Site settings
course_name: DSC 291 - Applied Privacy Research in Data Science
course_description: ""
course_semester: "Winter 2025"

baseurl: "/DSC291WI25" # the subpath of your site, e.g. /blog/
url: "http://haojian.github.io" # the base hostname & protocol for your site

schoolname: "University of California San Diego"
schoolurl: "https://ucsd.edu/"
twitter_username: haojian_jin 

address: |
    9500 Gilman Dr
    La Jolla
    CA 92093

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: false
    lectures:
        output: true
    assignments:
        output: false
    announcements:
        output: false


defaults:

